name: Terraform Destroy AWS Infra
run-name: Terraform destroy AWS Infra
on: 
    workflow_dispatch:
jobs:
    terraform-destroy:
        runs-on: ubuntu-latest
        steps: 
        -  name: Configure AWS credentials
           uses: aws-actions/configure-aws-credentials@v4
           with: 
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: eu-west-2
        
        -  name: Terraform Setup
           uses: hashicorp/setup-terraform@v3
           with:
            terraform_version: 1.4.6
        
        -  name: Terraform destroy
           run: |
              terraform destroy
        
