name: Terraform Destroy AWS Infra
run-name: Terraform destroy AWS Infra
on: 
    workflow_dispatch:
jobs:
    terraform-destroy:
        runs-on: ubuntu-latest
        steps: 
        -  name: Configure AWS credentials
           uses: aws-actions/configure-aws-credentials@v4
           with: 
            role-to-assume: ${{ secrets.AWS_ROLE }}
            aws-region: ${{ secrets.AWS_REGION }}
            role-session-name: Github-OIDC-TERRAFORM
            
        
        -  name: Terraform Setup
           uses: hashicorp/setup-terraform@v3
           with:
            terraform_version: 1.4.6
        
        -  name: Terraform destroy
           run: |
              terraform destroy
        
